create table if not exists public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, date_of_birth date, role text not null default 'student' check (role in ('student','parent')), created_at timestamptz default now());
create table if not exists public.subjects (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, grade text, progress integer default 0, created_at timestamptz default now());
create table if not exists public.materials (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subject_id uuid not null references public.subjects(id) on delete cascade, name text not null, storage_path text, extracted_text text, created_at timestamptz default now());
create table if not exists public.exams (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subject_id uuid not null references public.subjects(id) on delete cascade, title text not null, questions jsonb not null, score integer, completed_at timestamptz, created_at timestamptz default now());
create table if not exists public.tasks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, subject_id uuid references public.subjects(id) on delete cascade, title text not null, due_date date not null, completed boolean default false, created_at timestamptz default now());
create table if not exists public.parent_links (id uuid primary key default gen_random_uuid(), parent_id uuid not null references auth.users(id) on delete cascade, child_id uuid not null references auth.users(id) on delete cascade, status text default 'pending' check(status in ('pending','active','revoked')), created_at timestamptz default now(), unique(parent_id,child_id));
create table if not exists public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid unique not null references auth.users(id) on delete cascade, plan text not null check(plan in ('basic','full')), provider text not null default 'stripe', provider_customer_id text, provider_subscription_id text, status text not null default 'inactive', current_period_end timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());

alter table public.profiles enable row level security; alter table public.subjects enable row level security; alter table public.materials enable row level security; alter table public.exams enable row level security; alter table public.tasks enable row level security; alter table public.parent_links enable row level security; alter table public.subscriptions enable row level security;
create policy "own profile" on public.profiles for all using (id=auth.uid()) with check (id=auth.uid());
create policy "own subjects" on public.subjects for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "own materials" on public.materials for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "own exams" on public.exams for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "own tasks" on public.tasks for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy "own links" on public.parent_links for all using (parent_id=auth.uid() or child_id=auth.uid()) with check (parent_id=auth.uid() or child_id=auth.uid());
create policy "own subscription" on public.subscriptions for select using (user_id=auth.uid());
