'use client';
import {useEffect,useState} from 'react';

const initialSubjects=[{id:1,name:'Mathematics',progress:72,topics:14},{id:2,name:'Biology',progress:48,topics:11},{id:3,name:'History',progress:31,topics:9}];
const tabs=[['dashboard','Dashboard'],['subjects','Subjects'],['practice','Practice'],['exams','Mock Exams'],['materials','Materials'],['progress','Progress'],['tutor','AI Tutor']];

export default function Home(){
 const [tab,setTab]=useState('dashboard'); const [subjects,setSubjects]=useState(initialSubjects); const [materials,setMaterials]=useState([]); const [exam,setExam]=useState(null); const [answers,setAnswers]=useState({}); const [submitted,setSubmitted]=useState(false); const [questionCount,setQuestionCount]=useState(10); const [selectedSubject,setSelectedSubject]=useState('Mathematics'); const [prompt,setPrompt]=useState(''); const [chat,setChat]=useState([]);
 useEffect(()=>{try{setSubjects(JSON.parse(localStorage.getItem('tialo_subjects'))||initialSubjects);setMaterials(JSON.parse(localStorage.getItem('tialo_materials'))||[])}catch{}},[]);
 useEffect(()=>{localStorage.setItem('tialo_subjects',JSON.stringify(subjects))},[subjects]); useEffect(()=>{localStorage.setItem('tialo_materials',JSON.stringify(materials))},[materials]);
 const addSubject=()=>{const name=window.prompt('Subject name');if(name?.trim())setSubjects(s=>[...s,{id:Date.now(),name:name.trim(),progress:0,topics:0}])};
 const addMaterial=(e)=>{const files=[...e.target.files];setMaterials(m=>[...m,...files.map(f=>({id:Date.now()+Math.random(),name:f.name,size:f.size,subject:selectedSubject}))]);e.target.value=''};
 const makeExam=()=>{setSubmitted(false);setAnswers({});setExam(Array.from({length:questionCount},(_,i)=>({q:`${selectedSubject}: practice question ${i+1}. Which statement best demonstrates understanding of this topic?`,choices:['Concept A is correct','Concept B is correct','Concept C is correct','Concept D is correct'],correct:i%4})))};
 const submitExam=()=>{setSubmitted(true)};
 const send=()=>{if(!prompt.trim())return;const p=prompt.trim();setChat(c=>[...c,{role:'user',text:p},{role:'ai',text:'I can help you study this step by step. For the most accurate answers, add your course materials in Materials and select the relevant subject.'}]);setPrompt('')};
 return <div className="shell"><aside className="sidebar"><div className="brand">TI<span>ALO</span></div><nav className="nav">{tabs.map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav></aside><main className="main">
  <header className="top"><div><div className="eyebrow">AI Academic Coach</div><h1 className="title">{tabs.find(x=>x[0]===tab)?.[1]}</h1><p className="sub">A focused workspace for planning, practice and measurable progress.</p></div></header>
  {tab==='dashboard'&&<Dashboard subjects={subjects} setTab={setTab}/>} 
  {tab==='subjects'&&<Subjects subjects={subjects} onAdd={addSubject} setSelected={setSelectedSubject}/>} 
  {tab==='materials'&&<section className="panel"><div className="card"><h2>Course materials</h2><p className="muted">Add files to organize study material by subject. Files stay in this browser until a storage backend is connected.</p><select className="btn" value={selectedSubject} onChange={e=>setSelectedSubject(e.target.value)}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select><div className="file" style={{marginTop:15}}><p><b>Drop or select materials</b></p><p className="muted">PDF, DOCX, PPTX, TXT and other course files</p><input type="file" multiple onChange={addMaterial}/></div></div><div className="section card"><h2>Library</h2>{materials.length?<div className="list">{materials.map(m=><div className="row" key={m.id}><div><b>{m.name}</b><div className="muted">{m.subject} · {Math.round(m.size/1024)} KB</div></div><span className="pill">Material</span></div>)}</div>:<p className="muted">No materials yet. Add your first course file above.</p>}</div></section>}
  {tab==='practice'&&<Practice subjects={subjects} selectedSubject={selectedSubject} setSelectedSubject={setSelectedSubject} setSubjects={setSubjects}/>} 
  {tab==='exams'&&<section className="panel"><div className="card"><h2>Subject Mock Exam</h2><p className="muted">Generate a focused exam for one subject, take it, then review your result.</p><div className="actions"><select className="btn" value={selectedSubject} onChange={e=>setSelectedSubject(e.target.value)}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select><select className="btn" value={questionCount} onChange={e=>setQuestionCount(+e.target.value)}><option value="5">5 questions</option><option value="10">10 questions</option><option value="20">20 questions</option></select><button className="btn blue" onClick={makeExam}>Start mock exam</button></div></div>{exam&&<div className="section card">{exam.map((q,i)=><div key={i} className="row" style={{display:'block'}}><div className="muted">Question {i+1} of {exam.length}</div><div className="examq">{q.q}</div><div className="choices">{q.choices.map((c,j)=><button key={j} className={'choice '+(answers[i]===j?'selected':'')} onClick={()=>!submitted&&setAnswers(a=>({...a,[i]:j}))}>{c}</button>)}</div></div>)}<button className="btn primary" onClick={submitExam} disabled={submitted}>{submitted?'Submitted':'Submit exam'}</button>{submitted&&<div className="notice">Result: {exam.filter((q,i)=>answers[i]===q.correct).length}/{exam.length} correct. Keep practicing the topics you missed.</div>}</div>}</section>}
  {tab==='progress'&&<Progress subjects={subjects}/>} 
  {tab==='tutor'&&<section className="panel"><div className="card"><h2>AI Tutor</h2><p className="muted">Ask for explanations, examples, revision plans or study guidance.</p><div className="list" style={{marginTop:18}}>{chat.map((m,i)=><div key={i} className="notice"><b>{m.role==='user'?'You':'TIALO'}</b><div>{m.text}</div></div>)}</div><div className="actions"><input className="textarea" style={{minHeight:52}} value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&(e.preventDefault(),send())} placeholder="Ask TIALO anything about your studies…"/><button className="btn blue" onClick={send}>Send</button></div></div></section>}
 </main></div>
}
function Dashboard({subjects,setTab}){const avg=Math.round(subjects.reduce((a,s)=>a+s.progress,0)/subjects.length);return <><div className="grid"><div className="card"><div className="muted">Overall progress</div><div className="stat">{avg}%</div></div><div className="card"><div className="muted">Subjects</div><div className="stat">{subjects.length}</div></div><div className="card"><div className="muted">Study streak</div><div className="stat">0 days</div></div><div className="card"><div className="muted">Materials</div><div className="stat">—</div></div></div><section className="section"><h2>Your subjects</h2><div className="subjects">{subjects.map(s=><div className="card subject" key={s.id}><h3>{s.name}</h3><div className="muted">{s.topics} topics</div><div className="bar"><i style={{width:s.progress+'%'}}/></div><div className="actions"><span className="pill">{s.progress}% complete</span><button className="btn" onClick={()=>setTab('practice')}>Practice</button></div></div>)}</div></section><section className="section card"><h2>Continue studying</h2><p className="muted">Choose a subject to practice or add materials to make your study sessions more relevant.</p><div className="actions"><button className="btn blue" onClick={()=>setTab('practice')}>Practice now</button><button className="btn" onClick={()=>setTab('materials')}>Add materials</button><button className="btn" onClick={()=>setTab('exams')}>Take a mock exam</button></div></section></>}
function Subjects({subjects,onAdd,setSelected}){return <section className="panel"><div className="actions" style={{marginBottom:15}}><button className="btn blue" onClick={onAdd}>+ Add subject</button></div><div className="subjects">{subjects.map(s=><div className="card subject" key={s.id}><h3>{s.name}</h3><p className="muted">Progress and practice are tracked separately for each subject.</p><div className="bar"><i style={{width:s.progress+'%'}}/></div><div className="actions"><button className="btn" onClick={()=>setSelected(s.name)}>Select</button></div></div>)}</div></section>}
function Practice({subjects,selectedSubject,setSelectedSubject,setSubjects}){const [done,setDone]=useState(false);return <section className="panel"><div className="card"><h2>Practice session</h2><div className="actions"><select className="btn" value={selectedSubject} onChange={e=>{setSelectedSubject(e.target.value);setDone(false)}}>{subjects.map(s=><option key={s.id}>{s.name}</option>)}</select></div><div className="notice" style={{marginTop:18}}><b>Question</b><div className="examq">What is the best next step when studying {selectedSubject}?</div><div className="choices"><button className={'choice '+(done?'selected':'')} onClick={()=>setDone(true)}>Explain the concept, test recall, then review mistakes.</button><button className="choice">Read everything once without testing yourself.</button><button className="choice">Skip difficult topics indefinitely.</button></div></div>{done&&<><p>Correct. Active recall plus review is a strong study loop.</p><button className="btn blue" onClick={()=>setSubjects(ss=>ss.map(s=>s.name===selectedSubject?{...s,progress:Math.min(100,s.progress+2)}:s))}>Mark session complete</button></>}</div></section>}
function Progress({subjects}){return <section className="panel"><div className="card"><h2>Progress overview</h2><div className="list">{subjects.map(s=><div className="row" key={s.id}><div><b>{s.name}</b><div className="muted">{s.topics} topics tracked</div></div><div style={{minWidth:180}}><div className="bar"><i style={{width:s.progress+'%'}}/></div><b>{s.progress}%</b></div></div>)}</div></div></section>}
